// <auto-generated />
using System;
using CamRent_Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CamRent_Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CamRentDbContext))]
    [Migration("20251119103217_Remove_Quantity")]
    partial class Remove_Quantity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CamRent_Domain.Entities.Accessory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseDailyRate")
                        .HasColumnType("numeric")
                        .HasColumnName("base_daily_rate");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<decimal?>("DepositCapMaxVnd")
                        .HasColumnType("numeric")
                        .HasColumnName("deposit_cap_max_vnd");

                    b.Property<decimal?>("DepositCapMinVnd")
                        .HasColumnType("numeric")
                        .HasColumnName("deposit_cap_min_vnd");

                    b.Property<decimal>("DepositPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("deposit_percent");

                    b.Property<decimal>("EstimatedValueVnd")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_value_vnd");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confirmed");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<decimal>("PlatformFeePercent")
                        .HasColumnType("numeric")
                        .HasColumnName("platform_fee_percent");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<string>("SpecsJson")
                        .HasColumnType("text")
                        .HasColumnName("specs_json");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("Variant")
                        .HasColumnType("text")
                        .HasColumnName("variant");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("accessories");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("PickupAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pickup_at");

                    b.Property<Guid?>("RenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("renter_id");

                    b.Property<DateTime>("ReturnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("return_at");

                    b.Property<decimal>("SnapshotBaseDailyRate")
                        .HasColumnType("numeric")
                        .HasColumnName("snapshot_base_daily_rate");

                    b.Property<decimal>("SnapshotDepositAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("snapshot_deposit_amount");

                    b.Property<decimal>("SnapshotDepositPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("snapshot_deposit_percent");

                    b.Property<decimal>("SnapshotPlatformFeePercent")
                        .HasColumnType("numeric")
                        .HasColumnName("snapshot_platform_fee_percent");

                    b.Property<decimal>("SnapshotRentalTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("snapshot_rental_total");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("StaffId");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.BookingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccessoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("accessory_id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid?>("CameraId")
                        .HasColumnType("uuid")
                        .HasColumnName("camera_id");

                    b.Property<Guid?>("ComboId")
                        .HasColumnType("uuid")
                        .HasColumnName("combo_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("deposit_amount");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CameraId");

                    b.HasIndex("ComboId");

                    b.ToTable("booking_items");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("branches");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Camera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseDailyRate")
                        .HasColumnType("numeric")
                        .HasColumnName("base_daily_rate");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<decimal?>("DepositCapMaxVnd")
                        .HasColumnType("numeric")
                        .HasColumnName("deposit_cap_max_vnd");

                    b.Property<decimal?>("DepositCapMinVnd")
                        .HasColumnType("numeric")
                        .HasColumnName("deposit_cap_min_vnd");

                    b.Property<decimal>("DepositPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("deposit_percent");

                    b.Property<decimal>("EstimatedValueVnd")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_value_vnd");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confirmed");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<decimal>("PlatformFeePercent")
                        .HasColumnType("numeric")
                        .HasColumnName("platform_fee_percent");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<string>("SpecsJson")
                        .HasColumnType("text")
                        .HasColumnName("specs_json");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("Variant")
                        .HasColumnType("text")
                        .HasColumnName("variant");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("cameras");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Combo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<decimal?>("DepositOverride")
                        .HasColumnType("numeric")
                        .HasColumnName("deposit_override");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confirmed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("PriceOverride")
                        .HasColumnType("numeric")
                        .HasColumnName("price_override");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.ToTable("combos");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.ComboItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccessoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("accessory_id");

                    b.Property<Guid?>("CameraId")
                        .HasColumnType("uuid")
                        .HasColumnName("camera_id");

                    b.Property<Guid>("ComboId")
                        .HasColumnType("uuid")
                        .HasColumnName("combo_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryId");

                    b.HasIndex("CameraId");

                    b.HasIndex("ComboId");

                    b.ToTable("combo_items");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("SignedFileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signed_file_url");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid?>("VerificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("verification_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("VerificationId");

                    b.ToTable("contracts");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.ContractEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_json");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("contract_events");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.ContractSigner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("SignOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sign_order");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("contract_signers");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.ContractTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TemplateUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("contract_templates");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.DeliveryTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<decimal?>("DeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("delivery_fee");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TrackingCode")
                        .HasColumnType("text")
                        .HasColumnName("tracking_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeUserId");

                    b.HasIndex("BookingId");

                    b.ToTable("delivery_tasks");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.DeviceCategoryLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccessoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("accessory_id");

                    b.Property<Guid?>("CameraId")
                        .HasColumnType("uuid")
                        .HasColumnName("camera_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryId");

                    b.HasIndex("CameraId");

                    b.HasIndex("CategoryId");

                    b.ToTable("device_categories");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("disputes");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.DisputeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("DisputeId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispute_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("DisputeId");

                    b.ToTable("dispute_items");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.FileAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .HasColumnType("text")
                        .HasColumnName("owner_type");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("files");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.HandoverReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("ConditionNote")
                        .HasColumnType("text")
                        .HasColumnName("condition_note");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("HandoverAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handover_at");

                    b.Property<Guid?>("InspectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_id");

                    b.Property<string>("ItemsJson")
                        .HasColumnType("text")
                        .HasColumnName("items_json");

                    b.Property<string>("PartySignatureUrl")
                        .HasColumnType("text")
                        .HasColumnName("party_signature_url");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("party_type");

                    b.Property<string>("ReceiptPdfUrl")
                        .HasColumnType("text")
                        .HasColumnName("receipt_pdf_url");

                    b.Property<string>("StaffSignatureUrl")
                        .HasColumnType("text")
                        .HasColumnName("staff_signature_url");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ContractId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InspectionId");

                    b.HasIndex("UserId");

                    b.ToTable("handover_receipts");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccessoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("accessory_id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid?>("CameraId")
                        .HasColumnType("uuid")
                        .HasColumnName("camera_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<bool?>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<DateTime?>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<Guid?>("VerificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("verification_id");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryId");

                    b.HasIndex("BookingId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CameraId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("VerificationId");

                    b.ToTable("inspections");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AuthorizedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("authorized_amount");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<decimal>("CapturedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("captured_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderPaymentId")
                        .HasColumnType("text")
                        .HasColumnName("provider_payment_id");

                    b.Property<decimal>("RefundedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("refunded_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.PaymentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("BankCode")
                        .HasColumnType("text")
                        .HasColumnName("bank_code");

                    b.Property<string>("CardType")
                        .HasColumnType("text")
                        .HasColumnName("card_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_data");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseCode")
                        .HasColumnType("text")
                        .HasColumnName("response_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TransactionNo")
                        .HasColumnType("text")
                        .HasColumnName("transaction_no");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("RequestHash")
                        .IsUnique();

                    b.ToTable("payment_events");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.PaymentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<decimal>("CapturedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("captured_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("RefundedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("refunded_amount");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("payment_lines");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.ResetPasswordToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("reset_password_tokens");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("ModerationNotes")
                        .HasColumnType("text")
                        .HasColumnName("moderation_notes");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_staff_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetAccessoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_accessory_id");

                    b.Property<Guid?>("TargetCameraId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_camera_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("ReviewedByStaffId");

                    b.HasIndex("TargetAccessoryId");

                    b.HasIndex("TargetCameraId");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.SeedHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SeedHistories", (string)null);
                });

            modelBuilder.Entity("CamRent_Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankAccountName")
                        .HasColumnType("text")
                        .HasColumnName("bank_account_name");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("text")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankName")
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kyc_status");

                    b.Property<string>("NationalIdNumber")
                        .HasColumnType("text")
                        .HasColumnName("national_id_number");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.UserBranchMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("branch_memberships");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.UserRoleMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.VerificationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inspection_date");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("StaffId");

                    b.ToTable("verification_requests");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.VerificationRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccessoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("accessory_id");

                    b.Property<Guid?>("CameraId")
                        .HasColumnType("uuid")
                        .HasColumnName("camera_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("VerificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("verification_id");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryId");

                    b.HasIndex("CameraId");

                    b.HasIndex("VerificationId");

                    b.ToTable("verification_request_items");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Accessory", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("CamRent_Domain.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId");

                    b.Navigation("Branch");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Booking", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Branch", "Branch")
                        .WithMany("Bookings")
                        .HasForeignKey("BranchId");

                    b.HasOne("CamRent_Domain.Entities.User", "Renter")
                        .WithMany("RenterBookings")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("CamRent_Domain.Entities.User", "Staff")
                        .WithMany("StaffBookings")
                        .HasForeignKey("StaffId");

                    b.OwnsOne("CamRent_Domain.Common.Address", "Location", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("Branch");

                    b.Navigation("Location");

                    b.Navigation("Renter");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.BookingItem", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Accessory", "Accessory")
                        .WithMany()
                        .HasForeignKey("AccessoryId");

                    b.HasOne("CamRent_Domain.Entities.Booking", "Booking")
                        .WithMany("Items")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamRent_Domain.Entities.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId");

                    b.HasOne("CamRent_Domain.Entities.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboId");

                    b.Navigation("Accessory");

                    b.Navigation("Booking");

                    b.Navigation("Camera");

                    b.Navigation("Combo");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Branch", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("CamRent_Domain.Common.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("BranchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BranchId");

                            b1.ToTable("branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Camera", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("CamRent_Domain.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId");

                    b.Navigation("Branch");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Category", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.ComboItem", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Accessory", "Accessory")
                        .WithMany()
                        .HasForeignKey("AccessoryId");

                    b.HasOne("CamRent_Domain.Entities.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId");

                    b.HasOne("CamRent_Domain.Entities.Combo", "Combo")
                        .WithMany("Items")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accessory");

                    b.Navigation("Camera");

                    b.Navigation("Combo");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Contract", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId");

                    b.HasOne("CamRent_Domain.Entities.ContractTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamRent_Domain.Entities.VerificationRequest", "Verification")
                        .WithMany()
                        .HasForeignKey("VerificationId");

                    b.Navigation("Booking");

                    b.Navigation("Template");

                    b.Navigation("Verification");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.ContractEvent", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Contract", "Contract")
                        .WithMany("Events")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.ContractSigner", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Contract", "Contract")
                        .WithMany("Signers")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.DeliveryTask", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.User", "AssigneeUser")
                        .WithMany()
                        .HasForeignKey("AssigneeUserId");

                    b.HasOne("CamRent_Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CamRent_Domain.Common.Address", "DropoffAddress", b1 =>
                        {
                            b1.Property<Guid>("DeliveryTaskId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DeliveryTaskId");

                            b1.ToTable("delivery_tasks");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryTaskId");
                        });

                    b.OwnsOne("CamRent_Domain.Common.Address", "PickupAddress", b1 =>
                        {
                            b1.Property<Guid>("DeliveryTaskId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DeliveryTaskId");

                            b1.ToTable("delivery_tasks");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryTaskId");
                        });

                    b.Navigation("AssigneeUser");

                    b.Navigation("Booking");

                    b.Navigation("DropoffAddress");

                    b.Navigation("PickupAddress");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.DeviceCategoryLink", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Accessory", "Accessory")
                        .WithMany("Categories")
                        .HasForeignKey("AccessoryId");

                    b.HasOne("CamRent_Domain.Entities.Camera", "Camera")
                        .WithMany("Categories")
                        .HasForeignKey("CameraId");

                    b.HasOne("CamRent_Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accessory");

                    b.Navigation("Camera");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Dispute", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.DisputeItem", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Dispute", "Dispute")
                        .WithMany("Items")
                        .HasForeignKey("DisputeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispute");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.HandoverReceipt", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("CamRent_Domain.Entities.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamRent_Domain.Entities.User", "Staff")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("CamRent_Domain.Entities.Inspection", "Inspection")
                        .WithMany()
                        .HasForeignKey("InspectionId");

                    b.HasOne("CamRent_Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Branch");

                    b.Navigation("Contract");

                    b.Navigation("Inspection");

                    b.Navigation("Staff");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Inspection", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Accessory", "Accessory")
                        .WithMany()
                        .HasForeignKey("AccessoryId");

                    b.HasOne("CamRent_Domain.Entities.Booking", "Booking")
                        .WithMany("Inspections")
                        .HasForeignKey("BookingId");

                    b.HasOne("CamRent_Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("CamRent_Domain.Entities.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId");

                    b.HasOne("CamRent_Domain.Entities.User", "Staff")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("CamRent_Domain.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.HasOne("CamRent_Domain.Entities.VerificationRequest", "Verification")
                        .WithMany("Inspections")
                        .HasForeignKey("VerificationId");

                    b.Navigation("Accessory");

                    b.Navigation("Booking");

                    b.Navigation("Branch");

                    b.Navigation("Camera");

                    b.Navigation("Manager");

                    b.Navigation("Staff");

                    b.Navigation("Verification");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Payment", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.PaymentLine", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Payment", "Payment")
                        .WithMany("Lines")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.ResetPasswordToken", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Review", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamRent_Domain.Entities.User", "ReviewedByStaff")
                        .WithMany()
                        .HasForeignKey("ReviewedByStaffId");

                    b.HasOne("CamRent_Domain.Entities.Accessory", "TargetAccessory")
                        .WithMany()
                        .HasForeignKey("TargetAccessoryId");

                    b.HasOne("CamRent_Domain.Entities.Camera", "TargetCamera")
                        .WithMany()
                        .HasForeignKey("TargetCameraId");

                    b.Navigation("AuthorUser");

                    b.Navigation("ReviewedByStaff");

                    b.Navigation("TargetAccessory");

                    b.Navigation("TargetCamera");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.User", b =>
                {
                    b.OwnsOne("CamRent_Domain.Common.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.UserBranchMembership", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Branch", "Branch")
                        .WithMany("UserMemberships")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamRent_Domain.Entities.User", "User")
                        .WithMany("BranchMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.UserRoleMapping", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.VerificationRequest", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("CamRent_Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("CamRent_Domain.Entities.User", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");

                    b.Navigation("Branch");

                    b.Navigation("Owner");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.VerificationRequestItem", b =>
                {
                    b.HasOne("CamRent_Domain.Entities.Accessory", "Accessory")
                        .WithMany()
                        .HasForeignKey("AccessoryId");

                    b.HasOne("CamRent_Domain.Entities.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId");

                    b.HasOne("CamRent_Domain.Entities.VerificationRequest", "VerificationRequest")
                        .WithMany("Items")
                        .HasForeignKey("VerificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accessory");

                    b.Navigation("Camera");

                    b.Navigation("VerificationRequest");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Accessory", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Booking", b =>
                {
                    b.Navigation("Inspections");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Branch", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Camera", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Combo", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Contract", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Signers");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Dispute", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.Payment", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.User", b =>
                {
                    b.Navigation("BranchMemberships");

                    b.Navigation("RenterBookings");

                    b.Navigation("Roles");

                    b.Navigation("StaffBookings");
                });

            modelBuilder.Entity("CamRent_Domain.Entities.VerificationRequest", b =>
                {
                    b.Navigation("Inspections");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
